CREATE TABLE agent_messages (
    id text PRIMARY KEY, user_id text NOT NULL, session_id text NOT NULL,
    role text NOT NULL, content text NOT NULL, created_at text NOT NULL,
    parts_json text, ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX agent_messages_session_order ON agent_messages (user_id, session_id, ordinal);

CREATE TABLE agent_runs (
    id text PRIMARY KEY, user_id text NOT NULL, session_id text NOT NULL,
    status text NOT NULL, created_at text NOT NULL,
    resume_attempts integer NOT NULL DEFAULT 0, retry_after text,
    context_json text NOT NULL DEFAULT '{}', lease_owner text, lease_expires_at text,
    initial_attempts integer NOT NULL DEFAULT 0, checkpoint_file text,
    last_resumed_job_id text, active_resume_job_id text,
    turn_start_seq integer NOT NULL DEFAULT 0,
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX agent_runs_session_order ON agent_runs (user_id, session_id, ordinal);
CREATE INDEX agent_runs_recovery ON agent_runs (status, retry_after, lease_expires_at);

CREATE TABLE agent_events (
    run_id text NOT NULL, seq integer NOT NULL, payload text NOT NULL,
    PRIMARY KEY (run_id, seq)
);
CREATE TABLE pi_sessions (
    session_id text PRIMARY KEY, user_id text NOT NULL, session_file text NOT NULL
);

CREATE TABLE agent_jobs (
    id text PRIMARY KEY, user_id text NOT NULL, run_id text, tool_call_id text,
    status text NOT NULL, progress integer NOT NULL, estimated_minutes integer NOT NULL,
    actual_minutes integer, artifacts text NOT NULL DEFAULT '[]',
    created_at text NOT NULL, input_json text, worker_id text,
    lease_expires_at text, simulation integer NOT NULL DEFAULT 0,
    attempts integer NOT NULL DEFAULT 0, lease_token text, first_claimed_at text,
    resource_requirements_json text NOT NULL DEFAULT
      '{"capability":"af3","gpu_count":1,"min_gpu_memory_mb":0}',
    gpu_accounting_status text NOT NULL DEFAULT 'reserved',
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    UNIQUE (run_id, tool_call_id)
);
CREATE INDEX agent_jobs_status_order ON agent_jobs (status, ordinal);
CREATE INDEX agent_jobs_worker_status ON agent_jobs (worker_id, status, ordinal);

CREATE TABLE agent_artifact_blobs (
    id text PRIMARY KEY, user_id text NOT NULL, job_id text NOT NULL,
    name text NOT NULL, kind text NOT NULL, size integer NOT NULL,
    sha256 text NOT NULL, content bytea NOT NULL, created_at text NOT NULL,
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX agent_artifact_blobs_job ON agent_artifact_blobs (user_id, job_id);

CREATE TABLE agent_approvals (
    id text PRIMARY KEY, user_id text NOT NULL, run_id text NOT NULL,
    tool_call_id text NOT NULL, estimated_minutes integer NOT NULL,
    status text NOT NULL, job_id text, created_at text NOT NULL,
    input_json text, ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    UNIQUE (run_id, tool_call_id)
);

CREATE TABLE agent_token_usage (
    user_id text NOT NULL, period text NOT NULL, used integer NOT NULL,
    PRIMARY KEY (user_id, period)
);
CREATE TABLE agent_token_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL, period text NOT NULL, kind text NOT NULL,
    amount integer NOT NULL, run_id text, created_at text NOT NULL,
    status text NOT NULL DEFAULT 'posted'
);
CREATE INDEX agent_token_entries_user_period ON agent_token_entries (user_id, period, id);
CREATE TABLE agent_token_limits (
    user_id text PRIMARY KEY, limit_value integer NOT NULL
);
CREATE TABLE agent_model_call_guards (
    call_id text PRIMARY KEY, user_id text NOT NULL, run_id text NOT NULL,
    prompt_bytes integer NOT NULL, max_output_tokens integer NOT NULL,
    reserved_tokens integer NOT NULL, status text NOT NULL, created_at text NOT NULL
);
CREATE TABLE agent_gpu_limits (
    user_id text PRIMARY KEY, limit_value integer NOT NULL
);
CREATE TABLE agent_request_keys (
    user_id text NOT NULL, session_id text NOT NULL, key text NOT NULL,
    request_hash text NOT NULL, run_id text NOT NULL,
    PRIMARY KEY (user_id, session_id, key)
);
CREATE TABLE agent_af3_request_keys (
    user_id text NOT NULL, key text NOT NULL, request_hash text NOT NULL,
    job_id text NOT NULL, created_at text NOT NULL,
    PRIMARY KEY (user_id, key)
);
CREATE TABLE agent_gpu_reconciliations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id text NOT NULL, user_id text NOT NULL, source text NOT NULL,
    previous_minutes integer, actual_minutes integer NOT NULL,
    reason text NOT NULL, created_at text NOT NULL
);

CREATE TABLE workspace_projects (
    id text PRIMARY KEY, user_id text NOT NULL, name text NOT NULL,
    description text NOT NULL, archived_at text, icon text NOT NULL DEFAULT 'folder',
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX workspace_projects_user_order ON workspace_projects (user_id, ordinal);
CREATE TABLE workspace_sessions (
    id text PRIMARY KEY, user_id text NOT NULL, project_id text NOT NULL,
    title text NOT NULL, archived_at text,
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX workspace_sessions_project_order ON workspace_sessions (user_id, project_id, ordinal);
CREATE TABLE workspace_project_skills (
    user_id text NOT NULL, project_id text NOT NULL, skill_id text NOT NULL,
    is_default integer NOT NULL, position integer NOT NULL,
    PRIMARY KEY (user_id, project_id, skill_id)
);

CREATE TABLE core_schema_migrations (
    version integer PRIMARY KEY, applied_at text NOT NULL, description text NOT NULL
);
