CREATE TABLE component_schema_migrations (
    component text NOT NULL, version integer NOT NULL, applied_at text NOT NULL,
    description text NOT NULL, PRIMARY KEY (component, version)
);
CREATE TABLE account_tiers (
    user_id text PRIMARY KEY, tier text NOT NULL CHECK (tier IN ('guest', 'member')),
    last_seen_at text NOT NULL, cleanup_state text NOT NULL DEFAULT 'active'
);
CREATE TABLE guest_email_upgrades (
    user_id text PRIMARY KEY, email text NOT NULL, started_at text NOT NULL
);
CREATE TABLE guest_cleanup_claims (
    user_id text PRIMARY KEY, state text NOT NULL, claimed_at text NOT NULL
);
CREATE TABLE guest_cleanup_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_hash text NOT NULL, outcome text NOT NULL, created_at text NOT NULL
);

CREATE TABLE catalog_files (
    id text PRIMARY KEY, user_id text NOT NULL, name text NOT NULL,
    size integer NOT NULL, content text NOT NULL, raw_content bytea,
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX catalog_files_user_order ON catalog_files (user_id, ordinal);
CREATE TABLE catalog_skill_grants (
    user_id text PRIMARY KEY, skill_ids_json text NOT NULL
);
CREATE TABLE catalog_skill_versions (
    id text NOT NULL, version integer NOT NULL, name text NOT NULL,
    description text NOT NULL, tools_json text NOT NULL, instructions text NOT NULL,
    created_at text NOT NULL, PRIMARY KEY (id, version)
);

CREATE TABLE oauth_flows (
    state text PRIMARY KEY, verifier text NOT NULL, expires_at double precision NOT NULL,
    guest_user_id text
);
CREATE TABLE tool_runs (
    id text PRIMARY KEY, user_id text NOT NULL, tool text NOT NULL,
    title text NOT NULL, arguments_json text NOT NULL, result_json text NOT NULL,
    created_at text NOT NULL, project_id text,
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX tool_runs_user_order ON tool_runs (user_id, ordinal);

CREATE TABLE mcp_capacity_config (
    scope text PRIMARY KEY, max_calls integer NOT NULL
);
CREATE TABLE mcp_execution_leases (
    token text PRIMARY KEY, expires_at double precision NOT NULL
);
CREATE TABLE pdf_capacity_config (
    scope text PRIMARY KEY, max_calls integer NOT NULL
);
CREATE TABLE pdf_execution_leases (
    token text PRIMARY KEY, expires_at double precision NOT NULL
);
CREATE TABLE mcp_tool_calls (
    run_id text NOT NULL, tool_call_id text NOT NULL, name text NOT NULL,
    arguments_hash text NOT NULL, status text NOT NULL, result_json text,
    created_at text NOT NULL, ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    PRIMARY KEY (run_id, tool_call_id)
);
CREATE INDEX mcp_tool_calls_run_order ON mcp_tool_calls (run_id, ordinal);
CREATE TABLE internal_tool_auth (
    id text PRIMARY KEY, secret bytea NOT NULL
);
CREATE TABLE guest_creation_events (
    client_hash text NOT NULL, created_at bigint NOT NULL,
    ordinal bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX guest_creation_events_lookup ON guest_creation_events (client_hash, created_at);
