import React from "react";
import { createRoot } from "react-dom/client";
import { App } from "./app/App";
import "streamdown/styles.css";
import "katex/dist/katex.min.css";
import "./styles/base.css";
import "./styles/login.css";
import "./styles/layout.css";
import "./styles/sidebar.css";
import "./styles/main.css";
import "./styles/chat.css";
import "./styles/composer.css";
import "./styles/agent.css";
import "./styles/pages.css";
import "./styles/responsive.css";
import "./styles/mobile.css";
import "./styles/monochrome.css";
import "./styles/markdown.css";
import "./styles/mono-pages.css";
import "./styles/catalog.css";
import "./styles/scrollbars.css";
import "./styles/admin.css";
import "./styles/settings.css";
import "./styles/coral.css";

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
